version: '3'
services:
  node:
    container_name: dockerTraining
    volumes:
      - $PWD/app:/app
    image: arbildo/orbis-training-docker:2.0.0
    working_dir:
       /app
    ports:
      - 3030:1042
    command:
       npm start
